name: Build Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-windows:
    permissions:
        contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11
      
      - name: Build exe
        run: uv run --group build pyinstaller --clean -F -i="microscope.ico" --name splitToWells window.py
      
      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/splitToWells.exe

  build-macos:
    permissions:
        contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11
      
      - name: Build app
        run: |
          uv run --group build pyinstaller --clean --windowed -i="microscope.ico" --name splitToWells window.py
          cd dist
          zip -r splitToWells_mac.zip splitToWells.app
      
      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/splitToWells_mac.zip

  build-linux:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11
      
      - name: Build executable
        run: uv run --group build pyinstaller --clean -F --name splitToWells window.py
      
      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/splitToWells
