name: Build Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-windows:
    permissions:
        contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install ".[build]"
      
      - name: Build exe
        run: pyinstaller --clean -F -i="microscope.ico" --name splitToWells window.py
      
      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/splitToWells.exe

  build-macos:
    permissions:
        contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install ".[build]"
          pip install Pillow==12.2.0
      - name: Build app
        run: |
          pyinstaller --clean --windowed -i="microscope.ico" --name splitToWells window.py
          cd dist
          zip -r splitToWells_mac.zip splitToWells.app
      
      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/splitToWells_mac.zip

  build-linux:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install ".[build]"
      
      - name: Build executable
        run: pyinstaller --clean -F --name splitToWells window.py
      
      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/splitToWells